### PR TITLE
Implement CanNavigate function

### PR DESCRIPTION
**Pull request by neptunao**

### CODE REVIEW

**Comment by neptunao** [comment]
Is it ready to merge now?

**Comment by albrow** [comment]
@Neptunao yep. Thank you!

**Comment by neptunao** [comment]
btw, do you plan to release soon? It will be convinient for our project to use this function from master branch in your project :)

**Comment by albrow** [comment]
@Neptunao I already released it last week as version 0.3.0 :) I just haven't drafted the release notes yet.

Here's [the commit](https://github.com/go-humble/router/commit/149851060477f5e3d1b7b54acb33f383100ba719). The new method is [documented on godoc.org](https://godoc.org/github.com/go-humble/router#Router.CanNavigate).

If you are using something to version/manage dependencies, just update it to use version 0.3.0. If you are just using go get, running `go get -u github.com/go-humble/router` should do the trick.

**Pull request merged**
